{
"origin": "#[name:#names#]greeting# #explainer# #directions# #monotalk#",
"greeting": "Hi, my name is #name.capitalize#, and I will be your #guides# to the #internet# #day#.",
"explainer": "We will be visiting several #websites.s# together, you and I, on this journey, maybe into the past or into the present.",
"directions": "Please point your #technology# to #addresses#.",
"monotalk": "Does the #websites# seem to exist? Check https://archive.org/web/, go back to #year#. What do you see there, how is it different. Imagine the people who would visit this website, the people who built it, the people who ran it and added content to it. Why were they visiting, what did they want to see in the world, what were their days like? Each and every one of them woke up each day, the same as you and I, and went about their business, the same as you and I. This is not sublime, nor is it deep, but it is interesting. What were their conversations like and who did they talk to, and how did they feel. What did they think about the future, this future, that we are in now? Is this the narrative, or are you meant to be building one in your head, about these strangers on the #internet# 20 years ago. Where even are we right now? Is this some kind of simulation room? I don't remember how I got here. Anyway, now try #addresses# and repeat the exercise",
"names":[
  "abstract Expressionism",
  "academic",
  "action Painting",
  "aestheticism",
  "art Deco",
  "art Nouveau",
  "avant-garde",
  "barbizon School",
  "baroque",
  "bauhaus",
  "biedermeier",
  "caravaggisti",
  "stuckism",
  "superflat",
  "superstroke",
  "suprematism",
  "surrealism",
  "symbolism",
  "synchromism",
  "synthetism",
  "systems Art",
  "tachism",
  "tachisme",
  "tonalism",
  "video Art",
  "video Game Art",
  "vorticism",
  "young British Artists"
],
"guides":[
  "digiguide",
  "tour leader",
  "pied piper",
  "digital white rabit"
],
"year":[
  "1996",
  "1997",
  "1998",
  "1999",
  "2000"
],
"internet":[
  "internet",
  "cyberspace",
  "ARPANET",
  "National Information Infrastructure",
  "W3",
  "World Wide Web",
  "hyperspace",
  "infobahn",
  "information highway",
  "information superhighway",
  "online network",
  "the Net",
  "the Web",
  "interweb",
  "intertubes",
  "intersphere",
  "intertubes",
  "interblag",
  "blogonet",
  "webnet",
  "webweb",
  "websphere",
  "exonet",
  "exosphere"

],
"day":[
  "today",
  "tomorrow",
  "forever",
  "never",
  "Tuesday"
],
"websites":[
  "website",
  "cyberzone",
  "digiplace",
  "netlocale",
  "cyberisland",
  "webhome",
  "code temple",
  "cybercitie",
  "geocitie",
  "digital gopher hole",
  "IP addresse",
  "webserver",
  "digital club house"

],
"technology":[
  "web viewer",
  "digiscryer",
  "net window",
  "netscape navigator",
  "gopher bar",
  "mosaic window",
  "cyber eyes"

]
"addresses":[
  "http://altavista.digital.com",
  "http://www.excite.com",
  "http://infoseek.com",
  "http://www.lycos.com",
  "http://www.mckinley.com",
  "http://webcrawler.com",
  "http://intercome.com.au./wombat",
  "http://www.yahoo.com",
  "http://www.voyagerco.com/gg",
  "http://www.gslis.utexas.edu/~ldevlin/woc.html",
  "http://www.igc.apc.org/womensnet",
  "http://www.cadvision.com/ffap/engender/",
  "http://www.teleport.com/~wemoon/",
  "http://web.idirect.com/~mistress/escape.htm",
  "http://www.alternative-creations.com/",
  "http://nsns.com/single-search/",
  "http://www.enews.com:80/magazines/yellow_silk/",
  "http://www.feminist.org/news/news.html",
  "http://www.engr.unl.edu/~tory/alicia.html",
  "http://www.inform.umd.edu:8080/EdRes/Topic/WomensStudies/FilmReviews",
  "http://www.netcreations.com/mindgear",
  "http://www.uta.fi/~samu/SMARTS2.html",
  "http://www.webcom.com/~alcor/"

]

}
